/**
 * generated by Xtext
 */
package org.xtext.simplesonora.validation;

import org.eclipse.xtext.validation.Check;
import org.xtext.simplesonora.simpleSonora.Note;
import org.xtext.simplesonora.validation.AbstractSimpleSonoraValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class SimpleSonoraValidator extends AbstractSimpleSonoraValidator {
  @Check
  public void playNote(final Note note) {
  }
}
