/*
 * generated by Xtext
 */
package org.xtext.simplesonora.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SimpleSonoraUiModule extends org.xtext.simplesonora.ui.AbstractSimpleSonoraUiModule {
	public SimpleSonoraUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
