/*
 * generated by Xtext
 */
package org.xtext.simplesonora.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.simplesonora.ui.internal.SimpleSonoraActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SimpleSonoraExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SimpleSonoraActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SimpleSonoraActivator.getInstance().getInjector(SimpleSonoraActivator.ORG_XTEXT_SIMPLESONORA_SIMPLESONORA);
	}
	
}
