/*
 * generated by Xtext
 */
package org.xtext.simplesonora.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.simplesonora.services.SimpleSonoraGrammarAccess;

public class SimpleSonoraParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SimpleSonoraGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.simplesonora.parser.antlr.internal.InternalSimpleSonoraParser createParser(XtextTokenStream stream) {
		return new org.xtext.simplesonora.parser.antlr.internal.InternalSimpleSonoraParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public SimpleSonoraGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SimpleSonoraGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
