/*
 * generated by Xtext
 */
package org.xtext.simplesonora.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SimpleSonoraAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/xtext/simplesonora/parser/antlr/internal/InternalSimpleSonora.tokens");
	}
}
