/**
 * generated by Xtext
 */
package org.xtext.simplesonora.ui.contentassist;

import org.xtext.simplesonora.ui.contentassist.AbstractSimpleSonoraProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class SimpleSonoraProposalProvider extends AbstractSimpleSonoraProposalProvider {
}
