/*
 * generated by Xtext
 */
package org.xtext.simplesonora;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SimpleSonoraStandaloneSetup extends SimpleSonoraStandaloneSetupGenerated{

	public static void doSetup() {
		new SimpleSonoraStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

