/*
 * generated by Xtext
 */
package org.xtext.simplesonora;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SimpleSonoraRuntimeModule extends org.xtext.simplesonora.AbstractSimpleSonoraRuntimeModule {

}
